defaults:
  - base_mapping

_target_: rayfronts.mapping.SemanticPointCloud

# How many points to project per frame. Set to -1 to project all valid depth
# points.
max_pts_per_frame: 1000

# Length of the feature dimension to store. If smaller than encoder output 
# then PCA is used to compress. Set to -1 to use full encoder output.
stored_feat_dim: -1

feat_proj_basis_path: ${feat_proj_basis_path}

interp_mode: ${interp_mode}